site_name: Dan &  Angie's Bird Compendium

theme:
    name: 'material'
    features:
      - navigation.tracking
      - navigation.tabs
      - navigation.top
      - toc.integrate 
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        

# Extensions
markdown_extensions:
  - footnotes
  - meta
  - attr_list
  - md_in_html
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - tags
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
  
extra_css:
  - stylesheets/extra.css
  - stylesheets/uSwitchSelect.css
 
extra_javascript:
  - javascripts/extra.js